spring:
  application:
    name: manage-gateway

server:
  port: 9998

# CSE RPC 的配置项
# 应用名称
APPLICATION_ID: hoolink-development
# 微服务名称和版本号，微服务名称使用Spring Cloud的名称
service_description:
  name: ${spring.application.name}
  version: 1.0.0
  environment: development
# 服务中心的地址
servicecomb:
  service:
    registry:
      address: http://192.168.1.188:30100
      thread-count: 10
      instance:
        watch: false
  config:
    client:
      serverUri: http://192.168.1.188:30100
      refreshMode: 1
      refresh_interval: 15000
  # 对外发布的地址，端口号使用server.port
  rest:
    address: 0.0.0.0:${server.port}
    server:
      thread-count: 10
  credentials:
    accessKey: KZYQW9GQUYIU5G7ONCAV
    secretKey: 65nxJddaf9w17QNeVFi3Rwkp3Oh0fxBqiPvO6rHe
    akskCustomCipher: default
  # 线下开发，关闭监控数据上报
  monitor:
    client:
      enable: false
  # 处理链配置
  handler:
    chain:
      Provider:
        default: perf-stats,qps-flowcontrol-provider,bizkeeper-provider
      Consumer:
        default: auth,perf-stats,qps-flowcontrol-consumer,loadbalance,bizkeeper-consumer
  executors:
    default: cse.executor.groupThreadPool

  fallbackpolicy:
    Consumer:
      policy: customFallback