server:
  port: 9101
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  application:
    name: manage-gateway
  cloud:
    gateway:
      routes:
        - id: manage-base
          uri: lb://manage-base
          predicates:
            - Path=/manage-base/**
          filters:
            - StripPrefix=1
        - id: manage-edm
          uri: lb://manage-edm
          predicates:
            - Path=/manage-edm/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 192.168.0.170:8848